STARTING SCRIPT /home/hadoop/biggraphstage/kitescripts/big_data_tests/clustering_coefficient.groovy with params List((testDataSet,fake_westeros_v3_5m_145m))
2016-09-06 01:19:49,665 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-2 
Lost executor 2 on ip-10-169-165-112.ec2.internal: Container marked as failed: container_1473093320364_0032_01_000003 on host: ip-10-169-165-112.ec2.internal. Exit status: -100. Diagnostics: Container released on a *lost* node
2016-09-06 01:19:50,289 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-7 
Lost an executor 2 (already removed): Pending loss reason.
2016-09-06 01:21:46,260 - [ERROR] - from org.apache.spark.network.client.TransportClient in shuffle-server-2 
Failed to send RPC 5421064800360497921 to ip-10-146-66-158.ec2.internal/10.146.66.158:42084: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
2016-09-06 01:21:46,264 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-7 
Lost executor 4 on ip-10-109-193-82.ec2.internal: Slave lost
2016-09-06 01:21:46,306 - [ERROR] - from org.apache.spark.network.client.TransportClient in shuffle-server-2 
Failed to send RPC 7382668227197242161 to ip-10-146-66-158.ec2.internal/10.146.66.158:42084: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
2016-09-06 01:21:46,308 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-5 
Lost executor 1 on ip-10-146-66-158.ec2.internal: Slave lost
2016-09-06 01:21:47,185 - [ERROR] - from org.apache.spark.network.client.TransportClient in shuffle-server-2 
Failed to send RPC 6325711122750595015 to ip-10-146-66-158.ec2.internal/10.146.66.158:42084: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
2016-09-06 01:21:47,186 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-6 
Lost executor 3 on ip-10-35-196-138.ec2.internal: Slave lost
2016-09-06 01:23:50,751 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-3 
Lost executor 3 on ip-10-169-165-112.ec2.internal: Container marked as failed: container_1473093320364_0032_02_000004 on host: ip-10-169-165-112.ec2.internal. Exit status: -100. Diagnostics: Container released on a *lost* node
2016-09-06 01:24:23,827 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-3 
Lost an executor 3 (already removed): Pending loss reason.
2016-09-06 01:25:35,907 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-0 
Lost executor 1 on ip-10-155-37-30.ec2.internal: Container marked as failed: container_1473093320364_0032_02_000002 on host: ip-10-155-37-30.ec2.internal. Exit status: -100. Diagnostics: Container released on a *lost* node
2016-09-06 01:25:36,954 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-3 
Lost an executor 1 (already removed): Pending loss reason.
2016-09-06 01:33:19,534 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-2 
Lost executor 4 on ip-10-109-193-82.ec2.internal: Container marked as failed: container_1473093320364_0032_02_000009 on host: ip-10-109-193-82.ec2.internal. Exit status: -100. Diagnostics: Container released on a *lost* node
2016-09-06 01:33:20,218 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-5 
Lost an executor 4 (already removed): Pending loss reason.
FINISHED SCRIPT /home/hadoop/biggraphstage/kitescripts/big_data_tests/clustering_coefficient.groovy, took 902 seconds
